name: tg-playground-frontend

services:
  frontend:
    build:
      context: .
      target: base
    command: ["bun", "run", "dev"]
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: development
      TZ: Europe/Warsaw
      NEXT_PUBLIC_TIME_ZONE: Europe/Warsaw
    volumes:
      - ./src:/app/src
      - ./public:/app/public
